### ISSUE TITLE
Suggestion: global filters

### ISSUE THREAD

**Issue by cord** [nemrutco/nova-filterable-metrics#1]
Great stuff!

wonder if you could enhance the package so we can build dashboards on resource detail views with global filters (with pre-defined filter values)

![Monosnap 2020-01-03 11-01-43](https://user-images.githubusercontent.com/158588/71717451-711c6300-2e18-11ea-9fb0-434be1e97af6.png)

**Comment by nemrutco** [comment]
There is a milestone with this package to apply common filters to all metrics if one of the metric's filter changed. To do so, i need to figure out how to move filters to global filters. Or there can be a new package idea as the sample  you give. A single filter card apply to everything on the page that has same filter. I am open to PR/ideas if anything could be achieved with this package.

**Comment by cord** [comment]
> to apply common filters to all metrics if one of the metric's filter changed.
think this would be confusing. 

I tried myself to find a way of implementing it (but am missing the overview where to hook in), check:
https://github.com/laravel/nova-issues/issues/2014

One way would be to use the "filter-changed" event, capture the current filter configuration and then reload the metric using the filter parameters.

**Comment by nemrutco** [comment]
One way would be as you mentioned, listening global filter-changed event and reacting on each metrics but in that case each metrics should contains same filters as resource. Then you can check if metrics contains same filter then apply on it.  In Detail view, since there is no any filter functionality by Nova, it wouldn't work but if there is a package that applies global filter-changed on a single resource, you can catch that filter-changed event and apply on metrics as well. For now it's sounds to me it could be done by 2 separate packages which one is a filter card and another one is each metrics overwritten to listening filter-changed event.

**Comment by cord** [comment]
> In Detail view, since there is no any filter functionality by Nova,

the filters are loaded on the index view and using https://novapackages.com/packages/nrml-co/nova-big-filter the filters are shown on detail view (but not if the detail view is loaded directly)

the package https://novapackages.com/packages/digital-creative/nova-mega-filter loads filter through the cards method so there seems to be a way to load filters on demand


Am thinking of a package that would allow to build unlimited analystics dashboards (= resource) with widgets, which then are filterable with toolbar like this:
![dashboard-filter](https://user-images.githubusercontent.com/158588/71813573-429dc280-307a-11ea-9238-a128968b8847.png)

**Comment by nemrutco** [comment]
I am willing to implement such a package that will apply global filters to whichever part of the application is listening for that filter.  I need to arrange some time to work on it. I like the idea and i think it will help me to use it in some of the current projects i am working on.

**Comment by cord** [comment]
Great! Let me know if I can help you in any way?

Maybe we can get the necessary changes implemented as part of nova? 
See https://github.com/laravel/nova-issues/issues/2014

**Comment by nemrutco** [comment]
FYI i've tried some ideas and i think i got a way to listen global filters and react on them. Already implemented partly on one of my project. I am not sure how much it will impact on Nova's core functionality. But we might need some help from Nova team to do reuse of the existing functionality(ones we are not aware of). More likely we will end up with something that works for our goal and hopefully someone can help us to improve it.

**Comment by cord** [comment]
Thx for the update - this was published today, looks helpful?

https://novapackages.com/packages/square1-io/nova-metrics

**Comment by nemrutco** [comment]
> Thx for the update - this was published today, looks helpful?
> 
> https://novapackages.com/packages/square1-io/nova-metrics

Oh, this is a good news. it will help me to clear some junk tasks. Thanks..

**Comment by cord** [comment]
Check out this as well 

https://github.com/laravel/nova/pull/781

**Comment by nemrutco** [comment]
These are great. we might not do much at all now. i will play around some with the new updates. Let's see

**Comment by davidhemphill** [comment]
Hi! I'm not sure if this is where you ended up, but your custom tools and metric components can react when the filter values change by using Vuex. To decode the filters on the server, you'll probably have to do that manually. We have a PR to extract that out to a trait, but I don't think it's merged yet.

**Comment by cord** [comment]
Just following up - Something I can help with to get a global filter function?

**Comment by muzafferdede** [comment]
> Just following up - Something I can help with to get a global filter function?

@cord Sorry, I just got time to get back on this. I need to update my brain to start cooking something. It would be helpful if you could give me a breifly updates you come across related to your goal on this matter.

**Comment by glyphde** [comment]
Here's a hack to get a filter, though you have  to refresh the page. Perhpas you can add a trigger to do that somehow:
  ```
    public function calculate(NovaRequest $request) {
        $model = Transaction::make();
        $queries = [];
        parse_str(parse_url(request()->headers->get('referer'), PHP_URL_QUERY), $queries);
        $filters = json_decode(base64_decode($queries['transactions_filter']));
        foreach ($filters as $filter) {
            if (empty($filter->value)) {
                continue;
            }
            $model = (new $filter->class)->apply($request, $model, $filter->value);
        }

        return $this->count($request, $model)->format('0,0');
    }
```

**Comment by muzafferdede** [comment]
@glyphde not fan of using triggers and i believe Nova has something build in to do so. I will check it out. Thanks

**Comment by glyphde** [comment]
@muzafferdede   If you find out what "Nova has ... built in to do so", please let me know.  I imagine there might be a way to have nova automatically refresh the page when a filter is set, but it would be more elegant, if a card could be listening to the filter, and update itself in place.

**Comment by cord** [comment]
there is a `filter-changed` event utilized in https://novapackages.com/packages/nrml-co/nova-big-filter e.g. vendor/nrml-co/nova-big-filter/resources/js/components/Card.vue

**Comment by glyphde** [comment]
That's perfect. Thanks! filter-changed is used in nova's index template as well.

**Comment by muzafferdede** [comment]
![image](https://user-images.githubusercontent.com/5906125/80596340-ce3bc480-8a58-11ea-9c52-90b10e19587f.png)
Started working on this. So far all good.

**Comment by muzafferdede** [comment]
![image](https://user-images.githubusercontent.com/5906125/80643537-d9174900-8a9a-11ea-98b0-752396f8b060.png)

We got basic function working. Now testing..

**Comment by muzafferdede** [comment]
@cord  would like to take a look at what i come with? 

[Nova Global Filter](https://github.com/nemrutco/nova-global-filter)

It's not npm package yet so you need to use it through github. 

if you want to discuss, you can DM me on [twitter](https://twitter.com/muzafferdede)

**Comment by cord** [comment]
@muzafferdede 
GREAT STUFF! It works like a charm! Still can't understand why this is not the default behavior of nova

**Comment by muzafferdede** [comment]
@cord Glad to know it's works as you expected. To be honest, there was multiple way to achieve the goad you mentioned to have such a filtering but each way has its own pros and cons. 

Tracking state of filters is hardest part, I build my own tracking system so i can access it from anywhere. I wish to use with Nova's default tracking method but they are only available on Index views. But i believe it is possible. 

if @davidhemphill interested to implement such a thing, i will be happy to contribute. 

@cord feel free to close this issue since we have our new [Nova Global Filter](https://github.com/nemrutco/nova-global-filter) repo to discuss anything about it. :)

**Comment by bamatic** [comment]
how could i add filters to a dashboard ?

**Comment by muzafferdede** [comment]
> how could i add filters to a dashboard ?

i guess you are asking a use case for this package.
https://github.com/nemrutco/nova-global-filter
