### ISSUE TITLE
Previously selected date or dateRange is not shown/filled when Filters are opened next time.

### ISSUE THREAD

**Issue by chilio** [nemrutco/nova-filterable-metrics#12]
@muzafferdede thanks again for this nice plugin.
I've encountered 2 small things, which might improve overall UX a lot.
Steps to reproduce:
1. Open filters and select date range.
![image](https://user-images.githubusercontent.com/5613137/89065071-5f2d7f00-d36b-11ea-98ea-ba46fd7c77e2.png)
2. Click save.
3. Reopen filters -> old date range is still applied, but not shown
![image](https://user-images.githubusercontent.com/5613137/89065412-e7ac1f80-d36b-11ea-9a6f-b707ebc1c733.png)
Clicking save does not change anything, old date range is still applied.
Entering 0 removes filter.

It would be great to have both:
- Shown applied filter
- On clearing field -> filter removal executed, as in case of entering 0.

**Comment by MuzafferDede** [comment]
I will work on this. Probably going to be fixed in next release.

**Comment by MuzafferDede** [comment]
Fixed with  [v1.2.0](https://github.com/nemrutco/nova-filterable-metrics/releases/tag/v1.2.0)
