### ISSUE TITLE
Reset filter to null

### ISSUE THREAD

**Issue by ghost** [nemrutco/nova-filterable-metrics#15]
Laravel 7 , Nova v3.10.0

that will be great if you added "--" at first of every filter to reset it, like the default nova filter.

<img width="316" alt="Screen Shot 2020-09-28 at 2 13 40 PM" src="https://user-images.githubusercontent.com/56167610/94431146-3243ef80-0195-11eb-87ca-c297db950921.png">

**Comment by MuzafferDede** [comment]
Will be added in next release. Thanks.

**Comment by MuzafferDede** [comment]
Fixed with  [v1.2.0](https://github.com/nemrutco/nova-filterable-metrics/releases/tag/v1.2.0)
