### ISSUE TITLE
Issue with displaying value of default Date Field on edit page

### ISSUE THREAD

**Issue by martishevich** [nemrutco/nova-filterable-metrics#16]
nemrutco/nova-filterable-metrics v1.1.4
laravel/framework 7.28.3
laravel/nova 3.11.1

Laravel\Nova\Fields\Date doesn't display a value of field in the input on the edit page. On the details page, the field is displayed correctly.

Left side - edit page.
Right side - details page.
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/11298236/95027522-da7c1b80-06a1-11eb-90c7-8df0aa1c51f5.png">
I think some wrong with https://github.com/nemrutco/nova-filterable-metrics/blob/master/resources/js/components/DateTimePicker.vue file . 
Perhaps it overrides the standard functionality.

**Comment by GautierDele** [comment]
Can confirm that, no fix yet ?

This has made us going crazy finding this is the package that gave problem

**Comment by MuzafferDede** [comment]
I will look into this. Probably going to be fixed in next release.

**Comment by MuzafferDede** [comment]
Fixed with  [v1.2.0](https://github.com/nemrutco/nova-filterable-metrics/releases/tag/v1.2.0)
