### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by YarinceP** [nemrutco/nova-filterable-metrics#2]
I don't understand why this happens. Could you help me?

Thank you in advance for your help

**error output**

$ composer require nemrutco/nova-filterable-metrics
Using version ^1.0 for nemrutco/nova-filterable-metrics
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nemrutco/nova-filterable-metrics ^1.0 -> satisfiable by nemrutco/nova-filterable-metrics[v1.0.0].
    - nemrutco/nova-filterable-metrics v1.0.0 requires laravel/nova ~2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
![cap error](https://user-images.githubusercontent.com/28911286/73697121-6d902c00-46a3-11ea-8acf-dd1e8c9b0bf0.png)

**Comment by nemrutco** [comment]
> Problem 1
> - Installation request for nemrutco/nova-filterable-metrics ^1.0 -> satisfiable by nemrutco/nova-filterable-metrics[v1.0.0].
> - nemrutco/nova-filterable-metrics v1.0.0 requires laravel/nova ~2.0 -> no matching package found.


it's  already says that your version of Nova is not matching. You should have 2.0 or high version of nova
