### ISSUE TITLE
Passing selected filters for display in the card

### ISSUE THREAD

**Issue by novocent** [nemrutco/nova-filterable-metrics#6]
Can the value of a selected filter be passed for display on the metric card for a clearer UX?   I was able to alter the toasted notification to include the value rather than simply the filter name:
` this.$toasted.show("Filtered By " + event.target.selectedOptions[0].innerText, {
          type: "success", 
          duration : 2000
});`
But with multiple filters, I think that then metric card needs to also include the choices for clarity.

**Comment by muzafferdede** [comment]
Maybe in future could be implemented. I tried few things with the current setup but didn't make sense at some point. But i will keep in mind.
