### ISSUE TITLE
Update to Nova 3^

### ISSUE THREAD

**Issue by JoseLuisRNP** [nemrutco/nova-filterable-metrics#7]
The package will support Nova 3^ or still with only Nova 2 support?  Thanks

**Comment by muzafferdede** [comment]
Now it does support `^3.0` as well. You can update this package to `v1.2.0` version.

**Comment by muzafferdede** [comment]
Now it does support `^3.0` as well. You can update this package to `v1.1.0` version.

**Comment by JoseLuisRNP** [comment]
Nice news! Thanks @muzafferdede
