### ISSUE TITLE
Metric doesn't adjust view to filter

### ISSUE THREAD

**Issue by JoseLuisRNP** [nemrutco/nova-filterable-metrics#8]
I'm trying make a trend metric filterable between 2 dates, the filter works but de view of metric is too long, example:

Filtered between 1st march to today (view from the first day of db make)
![image](https://user-images.githubusercontent.com/40276399/80386211-5f6b3980-88a7-11ea-9589-e1652bff5aeb.png)

Expected: Adjust de view from 1st march to today. Something like
![image](https://user-images.githubusercontent.com/40276399/80387416-ea006880-88a8-11ea-9fdd-7c2b75520212.png)

The code:
Metrics\MyTrend.php -> method range() deleted.
```
use Nemrutco\Filterable\FilterableTrend;

class MyTrend extends Trend
{
    use FilterableTrend;
//Rest of code
public function filters()
    {
        return [
            (new Date)->range(),
        ];
    }
``` 

Filters\Date.php
```
class Date extends DateFilter
{
    public function apply(Request $request, $query, $value)
    {
       $start = Carbon::parse(substr($value, 0, 9));
       $end = Carbon::parse(substr($value, 14));
        return $query->whereBetween('published_at', [$start, $end]);
    }

    public function range()
    {
        return $this->withMeta(['mode' => 'range']);
    }

}
```

MyResource.php
```
public function cards(Request $request)
    {
        return [
            new MyTrend,
        ];
    }

 public function filters(Request $request)
    {
        return [
            (new Date)->range(),
        ];
    }
```

I'm forgetting something or the behavior expected is that de metric adjust de view to the range selected?
Thanks again.

**Comment by muzafferdede** [comment]
i am not sure how you use the dates in your example but i guess that's where it gets wrong. Try this

```php
class Date extends DateFilter
{
    public function apply(Request $request, $query, $value)
    {
        return $query->whereBetween('published_at`, [Carbon::parse($value[0])->startOfDay(),  Carbon::parse($value[1] ?? $value[0])->endOfDay()]);
    }

    public function range()
    {
        return $this->withMeta(['mode' => 'range']);
    }
}

**Comment by JoseLuisRNP** [comment]
`$value` return a string like `"2020-04-01 to 2020-04-28"`, i use substrings for that reason
```php
$start = Carbon::parse(substr($value, 0, 9));
$end = Carbon::parse(substr($value, 14));
```
It would return an array with the dates selected?

i'm on nova 3.4.1, laravel 7.8.1

**Comment by muzafferdede** [comment]
Oh right, forget to include this. 

`​$value​ ​=​ ​explode​(​"​ to ​"​, ​$value​)` to convert value to array

**Comment by JoseLuisRNP** [comment]
Yes, is the same case that write in my first comment.

It filter right, the graphic show the data filter, but my issue is that the total of graphic doesn't adapt to the selected dates filter.

Here the graphic with the dates filtered.
![image](https://user-images.githubusercontent.com/40276399/80478652-19b57c00-894e-11ea-806d-1360627d049b.png)

Here how in my opinion that graphic will be show with the dates filtered.
![image](https://user-images.githubusercontent.com/40276399/80478803-55e8dc80-894e-11ea-94bd-58928c322c44.png)

Both have the same range filtered, but I only fix the view with the range method of the metric. Example: 
 ```php
//MyTrend.php
public function ranges()
    {
        return [
            30 => '30'
        ];
    }
```
This will show only the last 30 days in view no matter how much earlier the date is filtered. Is it possible that this adapt dinamically from the range date selected in the date filter?
Thanks again

**Comment by muzafferdede** [comment]
did you see the commend in bottom of this package's Readme? 

> If you use ranges and a date filter, your date filter will be applied only within the selected Nova's range. So try to not use ranges and a date filter at same time.

Think about it, you set default range to 30 days in Nova's range filter and then another date filter to 60 days earlier. Nova will first filter 30 days, and then try to filter 60 days, but the earliest date is 30 days ago. So no matter what, date will not be set 60 days earlier. I hope it make sense to you.

**Comment by JoseLuisRNP** [comment]
Yes, of course, i read it and remove the range method. 
I tried with the empty array and get the same result.

Here all the archives.
Filter
```php
use Laravel\Nova\Filters\DateFilter;

class BetweenDates extends DateFilter
{
    public function apply(Request $request, $query, $value)
    {
        $value = explode(" to ", $value);

        return $query->whereBetween('published_at', [Carbon::parse($value[0])->startOfDay(),  Carbon::parse($value[1] ?? $value[0])->endOfDay()]);
    }

    public function range()
    {
        return $this->withMeta(['mode' => 'range']);
    }
}
```
Trend
```php
use Nemrutco\Filterable\FilterableTrend;

class IllustrationsPublishedPerDay extends Trend
{
    use FilterableTrend;

    public function calculate(NovaRequest $request)
    {
        return $this->countByDays($request, Illustration::class, 'published_at');
    }
    public function filters()
    {
        return [
            (new BetweenDates)->range(),
        ];
    }

    public function ranges()
    {
        return [];
    }

    public function cacheFor()
    {
        // return now()->addMinutes(5);
    }

    public function uriKey()
    {
        return 'illustrations-published-per-day';
    }

}
```
My resource
```php
all stuff....
public function cards(Request $request)
    {
        return [
            new IllustrationsPublishedPerDay,
        ];
    }

    public function filters(Request $request)
    {
        return [];
    }
```

I forgett something? I will try with a partition or value metric. In case that works in this metric I notify you

**Comment by muzafferdede** [comment]
hmm, looks fine. That's interesting. Let me know if you got some debug info like, if use without this package, how is the result?

**Comment by JoseLuisRNP** [comment]
With metrics value and metrics partition the package work fine.
It's seems only have the issue of adjust the range of trend metrics to the selected ranges.

The card withouth the package:
30 days
![image](https://user-images.githubusercontent.com/40276399/80503143-c3f2cb00-8971-11ea-9b05-c91a207550b4.png)
60 days
![image](https://user-images.githubusercontent.com/40276399/80503211-d967f500-8971-11ea-8775-214037abaf51.png)

As you can see, the total range of see is different in 30 days or 60 days.

With the package, it filter well the data between the dates. only show data of selected range, but the it's doesn't adjust the graphic with only the dates between the range.
![image](https://user-images.githubusercontent.com/40276399/80478652-19b57c00-894e-11ea-806d-1360627d049b.png)

Seems all it's working and only need to adjust something like the "zoom" of svg chart to see only the range of selected dates

**Comment by muzafferdede** [comment]
Alright, I will check this. I remember I didn't test trends too much, probably I missed something

**Comment by muzafferdede** [comment]
Just released an update `v1.1.1` which i upgraded all base to nova `3.0` and tested. All should be good. If not than you should deep dive in your code and see what is going on.

**Comment by JoseLuisRNP** [comment]
I update and work with the same issue for me,  your trend metric adjust the start of the view for the start day selected and finish of the view for the end day selected?

**Comment by muzafferdede** [comment]
Yeah, all good in my test. If you can't figure out why, do a screencast and reproduce the issue step by step and post here. Otherwise i can't help you. I can't find what is the issue in my end.

**Comment by JoseLuisRNP** [comment]
Finally my client looking around other solution without filter dates. Thanks for your work in my issue,

**Comment by Sehkmat** [comment]
Actually, there is still this problem.

The problem @JoseLuisRNP had is caused by Nova itself.

Using FilterableTrend just add a new where clause for the selected range. But it doesn't suppress the where clause added by the Nova Trend. Removing the function ranges() or returning an empty array doesn't change anything as the Trend still needs to have a start day and end day.

This ends up in the below query:
<img width="822" alt="Screenshot 2022-03-22 at 13 18 24" src="https://user-images.githubusercontent.com/12222956/159484947-34118c55-89ef-43ab-89c1-4bb89fb1f1f3.png">

You can see two where clause for the same field. The one I selected in the date range, and the one from the nova trend. But the trend add this where clause afterwards. So it's impossible to remove this clause in the custom daterange filter...
